### ISSUE TITLE
Feature Idea: Table of Contents

### ISSUE THREAD

**Issue by mrkhdly** [jeanfredrik/css-info-app#1]
**Feature Idea: Table of Contents**
Having a table of contents navigation generated which is fixed maybe to the side, so a user can quickly/easily got to a certain section of the page that is generated.

**Comment by jeanfredrik** [comment]
[Version 3](https://github.com/jeanfredrik/css-info-app/releases/tag/v3.0.0) is now out at https://css-info.jeanfredrik.com/ with a TOC sidebar. Let me know if you like it or if there’s something you would like me to change.
