### ISSUE TITLE
Feature Idea: specify CSS file via query param

### ISSUE THREAD

**Issue by justgage** [jeanfredrik/css-info-app#2]
This would be nice to send my co-workers to the latest css file and they could search it always being up to date.

**Comment by jeanfredrik** [comment]
I really like this idea, but there's a problem that I'm not sure how to solve.

The app needs to fetch the remote CSS somehow, but cross-site XHR requests are not allowed in most browsers. I think I can solve it by inserting a `<link rel="stylesheet">` tag and then use `document.styleSheets` (and the [CSSStyleSheet API](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet)) to fetch its contents. This would however already be parsed by the browser and I use a different parser, so I would have to stringify it and parse it again to get the right structure.

However, the parser I use (https://github.com/reworkcss/css) is no longer maintained and it would be a good idea to replace it anyway. There is an [npm package that creates a CSSOM](https://github.com/NV/CSSOM) (just like the browser), but it has some drawbacks, as mentioned in the readme.

So I’m open for other ideas on how to solve this before I start digging.

**Comment by justgage** [comment]
The easiest way is to have a server do it. They aren't restricted by cors.
Even heroku app would probably do. Ideally you could even cache the
results.

**Comment by jeanfredrik** [comment]
Apparently it was impossible to bypass access control even with the use of the `<link>` hack, so I had to use a CORS proxy instead. The feature is now implemented in version [2.0.0](https://github.com/jeanfredrik/css-info-app/releases/tag/v2.0.0) which is deployed to https://css-info.jeanfredrik.com/
